import { ingredientMacros } from "./ingredient-level-macros";

export type dishMacro = keyof typeof ingredientMacros;

export const dishMacros: Record<string, Partial<Record<dishMacro, number>>> = {
  chicken_adobo: {
    chicken_breast: 50,
    chicken_thigh: 50,
    chicken_wing: 50,
    chicken_drumstick: 50,
  },

  chicken_inasal: {
    chicken_thigh: 50,
  },

  arrozcaldo: {
  chicken: 50,
  jasmine_rice: 50,
  sweet_rice: 50,
  chicken_bouillon_cubes: 50,
  water: 50,
  garlic: 50,
  onion: 50,
  boiled_eggs: 50,
  green_onion: 50,
  ginger: 50,
  safflower: 50,
  fish_sauce: 50,
},

balbacua: {
  cow_trotters: 50,
  knorr_beef_cube: 50,
  lemongrass: 50,
  bell_pepper: 50,
  salted_black_beans: 50,
  green_onions: 50,
  jalapeno_peppers: 50,
  ground_black_pepper: 50,
  tomato_sauce: 50,
  water: 50,
  annatto_powder: 50,
  garlic: 50,
  onion: 50,
  ginger: 50,
  fish_sauce: 50,
  cooking_oil: 50,
},

bulalo: {
  beef_shank: 50,
  cabbage: 50,
  bok_choy: 50,
  corn: 50,
  whole_peppercorn: 50,
  green_onions: 50,
  onion: 50,
  water: 50,
  fish_sauce: 50,
},

champorado: {
  cocoa_powder: 50,
  glutinous_rice: 50,
  sugar: 50,
  water: 50,
  condensed_milk: 50,
},

chicken_tinola: {
  chicken: 50,
  green_papaya: 50,
  malunggay_leaves: 50,
  hot_pepper_leaves: 50,
  garlic: 50,
  onion: 50,
  ginger: 50,
  chicken_bouillon_cubes: 50,
  rice_wash: 50,
  water: 50,
  fish_sauce: 50,
  ground_black_pepper: 50,
  cooking_oil: 50,
},

daing_bangus: {
  milkfish: 50,
  white_vinegar: 50,
  crushed_peppercorn: 50,
  garlic: 50,
  cayenne_pepper_powder: 50,
  coarse_sea_salt: 50,
  cooking_oil: 50,
},

dinuguan: {
  pork: 50,
  vinegar: 50,
  long_green_pepper: 50,
  brown_sugar: 50,
  onion: 50,
  garlic: 50,
  cooking_oil: 50,
  water: 50,
  pork_blood: 50,
  pork_bouillon_cube: 50,
  salt: 50,
  pepper: 50,
},

halo_halo: {
  sugar_palm: 50,
  boiled_kidney_beans: 50,
  flat_rice_crisps: 50,
  coconut_gel: 50,
  ripe_jackfruit: 50,
  colored_gelatin: 50,
  tapioca_pearls: 50,
  sweetened_plantains: 50,
  macapuno: 50,
},

kansi: {
  beef_shank: 50,
  lemongrass: 50,
  plum_tomato: 50,
  long_green_chili: 50,
  hot_red_chili_pepper: 50,
  garlic: 50,
  yellow_onion: 50,
  annatto_oil: 50,
  beef_bouillon_cube: 50,
  sinigang_sa_sampaloc_mix: 50,
  unripe_jackfruit: 50,
  water: 50,
  fish_sauce: 50,
},

kare_kare: {
  oxtail: 50,
  banana_flower_bud: 50,
  pechay: 50,
  bok_choy: 50,
  string_beans: 50,
  eggplants: 50,
  ground_peanuts: 50,
  peanut_butter: 50,
  shrimp_paste: 50,
  water: 50,
  annatto_seeds: 50,
  toasted_ground_rice: 50,
  garlic: 50,
  onion: 50,
  salt: 50,
  pepper: 50,
},

kutsinta: {
  rice_flour: 50,
  all_purpose_flour: 50,
  brown_sugar: 50,
  water: 50,
  lye_water: 50,
  annatto_seeds: 50,
},

batchoy: {
  water: 50,
  miki_noodles: 50,
  pork: 50,
  pigs_intestines: 50,
  pig_liver: 50,
  salt: 50,
  ground_black_pepper: 50,
  sugar: 50,
  shrimp_paste: 50,
  onion_powder: 50,
  pork_cracklings: 50,
  spring_onion: 50,
  toasted_garlic: 50,
},

lumpia: {
  ground_pork: 50,
  carrot: 50,
  parsley: 50,
  salt: 50,
  sesame_oil: 50,
  garlic_powder: 50,
  ground_black_pepper: 50,
  lumpia_wrapper: 50,
  eggs: 50,
},

pancit_bihon: {
  pancit_bihon_noodles: 50,
  pork: 50,
  chicken: 50,
  snow_peas: 50,
  carrot: 50,
  cabbage: 50,
  celery_leaves: 50,
  onion: 50,
  garlic: 50,
  chicken_powder: 50,
  soy_sauce: 50,
  water: 50,
  cooking_oil: 50,
},

pancit_molo: {
  ground_pork: 50,
  shrimp: 50,
  wonton_wrappers: 50,
  yellow_onion: 50,
  garlic_powder: 50,
  sesame_oil: 50,
  egg: 50,
  salt: 50,
  ground_black_pepper: 50,
  rotisserie_chicken: 50,
  chicken_broth: 50,
  water: 50,
  scallions: 50,
  toasted_garlic: 50,
  fish_sauce: 50,
},

pinakbet: {
  lechon_kawali: 50,
  shrimp_bouillon_cube: 50,
  sitaw: 50,
  kalabasa: 50,
  okra: 50,
  chinese_eggplant: 50,
  ampalaya: 50,
  kamote: 50,
  tomato: 50,
  ginger: 50,
  onion: 50,
  garlic: 50,
  bagoong_alamang: 50,
  water: 50,
  cooking_oil: 50,
  ground_black_pepper: 50,
},

pork_adobo: {
  pork_belly: 50,
  garlic: 50,
  bay_leaves: 50,
  vinegar: 50,
  soy_sauce: 50,
  peppercorn: 50,
  water: 50,
  salt: 50,
},

pork_sinigang: {
  pork_belly: 50,
  kangkong_leaves: 50,
  long_green_chili_pepper: 50,
  tomato: 50,
  daikon_radish: 50,
  snake_beans: 50,
  onion: 50,
  okra: 50,
  taro: 50,
  water: 50,
  sinigang_sa_sampaloc_mix: 50,
  fish_sauce: 50,
  ground_black_pepper: 50,
},

pork_sisig: {
  pig_ears: 50,
  pig_snout: 50,
  pork_belly: 50,
  onion: 50,
  bay_leaves: 50,
  salt: 50,
  ginger: 50,
  water: 50,
},

pyanggang: {
  chicken_leg_quarters: 50,
  chicken_thighs: 50,
  burnt_coconut: 50,
  red_onion: 50,
  lemongrass: 50,
  luyang_dilaw: 50,
  garlic: 50,
  ginger: 50,
  cilantro_stems: 50,
  spring_onions: 50,
  canola_oil: 50,
  salt: 50,
  finger_chilies: 50,
  white_onion: 50,
  fish_sauce: 50,
  coconut_milk: 50,
  coconut_cream: 50,
},

satti: {
  beef: 50,
  chicken_wings: 50,
  coconut_milk: 50,
  barbecue_skewers: 50,
  annatto_powder: 50,
  lemon_juice: 50,
  water: 50,
  salt: 50,
  chicken_stock: 50,
  coconut_cream: 50,
  tomato: 50,
  japanese_taro: 50,
  bagoong: 50,
  peanut_butter: 50,
  curry_powder: 50,
  oil: 50,
  flour: 50,
  cornstarch: 50,
  white_sugar: 50,
  birds_eye_chilies: 50,
  ginger: 50,
  shallots: 50,
  turmeric: 50,
  dried_oregano: 50,
},

shrimp_sinigang: {
  shrimp: 50,
  sinigang_sa_sampaloc_mix: 50,
  kangkong: 50,
  snake_beans: 50,
  okra: 50,
  eggplant: 50,
  daikon_radish: 50,
  tomato: 50,
  long_green_pepper: 50,
  onion: 50,
  water: 50,
  fish_sauce: 50,
  ground_black_pepper: 50,
},

tiyula_itum: {
  chicken: 50,
  beef: 50,
  ginger: 50,
  garlic: 50,
  onion: 50,
  lemongrass: 50,
  burnt_coconut_meat_powder: 50,
  turmeric_powder: 50,
}
};
