import { ingredientMacros } from "./ingredient-level-macros";

export type dishMacro = keyof typeof ingredientMacros;

export const dishMacros: Record<string, Partial<Record<dishMacro, number>>> = {
  chicken_adobo: {
    chicken_breast: 50,
    chicken_thigh: 50,
    chicken_wing: 50,
    chicken_drumstick: 50,
  },

  chicken_inasal: {
    chicken_thigh: 113,
  },

  arrozcaldo: {
  chicken: 149,
  jasmine_rice: 78,
  sweet_rice: 78,
  chicken_bouillon_cubes: 20,
  water: 50,
  garlic: 6,
  onion: 50,
  boiled_eggs: 77,
  green_onion: 13,
  ginger: 2.5,
  safflower: 0.5,
  fish_sauce: 16,
},

balbacua: {
  cow_trotters: 376.5,
  knorr_beef_cube: 1.7,
  lemongrass: 7,
  bell_pepper: 25.5,
  salted_black_beans: 7.5,
  green_onions: 5.1,
  jalapeno_peppers: 7.5,
  ground_black_pepper: 0.39,
  tomato_sauce: 37.7,
  water: 400,
  annatto_powder: 0.83,
  garlic: 3.3,
  onion: 17,
  ginger: 1.7,
  fish_sauce: 16,
  cooking_oil: 6.8,
},

bulalo: {
  beef_shank: 227,
  cabbage: 100,
  bok_choy: 60,
  corn: 125,
  whole_peppercorn: 3.3,
  green_onions: 13,
  onion: 25,
  water: 241,
  fish_sauce: 16,
},

champorado: {
  cocoa_powder: 96,
  glutinous_rice: 66,
  sugar: 34,
  water: 281,
  condensed_milk: 15,
},

chicken_tinola: {
  chicken_generic_raw: 227,
  green_papaya: 100,
  malunggay_leaves: 5,
  hot_pepper_leaves: 2,
  garlic: 3,
  onion: 17,
  ginger: 5,
  chicken_bouillon_cubes: 20,
  white_rice: 161,
  water: 161,
  fish_sauce: 5,
  ground_black_pepper: 0.3,
  cooking_oil: 7,
},

daing_bangus: {
  milkfish_raw: 250,
  white_vinegar: 75,
  cracked_peppercorn: 1,
  garlic: 25,
  cayenne_pepper_powder: 0.2,
  coarse_sea_salt: 1.5,
  cooking_oil: 54,
},

dinuguan: {
  pork_shoulder: 77,
  pork_blood: 94,
  pork_ear: 36,
  vinegar: 41,
  long_green_pepper: 15,
  brown_sugar: 1.4,
  onion: 17,
  garlic: 3,
  cooking_oil: 7,
  beef_bouillon_cube: 20,
  salt: 1,
  black_pepper: 0.3,
},

halo_halo: {
  sugar_palm: 30,
  boiled_kidney_beans: 25,
  flat_rice_crisps: 10,
  coconut_gel: 20,
  ripe_jackfruit: 25,
  colored_gelatin: 15,
  tapioca_pearls: 20,
  sweetened_plantains: 20,
  macapuno: 20,
},

kansi: {
  beef_shank: 50,
  lemongrass: 50,
  plum_tomato: 50,
  long_green_chili: 50,
  hot_red_chili_pepper: 50,
  garlic: 50,
  yellow_onion: 50,
  annatto_oil: 50,
  beef_bouillon_cube: 50,
  sinigang_sa_sampaloc_mix: 50,
  unripe_jackfruit: 50,
  water: 50,
  fish_sauce: 50,
},

kare_kare: {
  oxtail: 227,
  banana_flower_bud: 40,
  pechay: 30,
  bok_choy: 30,
  string_beans: 30,
  eggplants: 67,
  ground_peanuts: 25,
  peanut_butter: 20,
  shrimp_paste: 20,
  water: 160,
  annatto_seeds: 10,
  toasted_ground_rice: 10,
  garlic: 2,
  onion: 10,
  salt: 2,
  pepper: 1,
},

kutsinta: {
  rice_flour: 30,
  all_purpose_flour: 10,
  brown_sugar: 35,
  water: 120,
  lye_water: 1,
  annatto_seeds: 1,
},


batchoy: {
  water: 280,
  miki_noodles: 77,
  pork: 77,
  pigs_intestines: 77,
  pig_liver: 18,
  salt: 1.5,
  ground_black_pepper: 0.25,
  sugar: 1.4,
  shrimp_paste: 1,
  onion_powder: 0.5,
  pork_cracklings: 10,
  spring_onion: 3,
  toasted_garlic: 5,
},

lumpia: {
  ground_pork: 113,
  carrot: 30,
  parsley: 8,
  salt: 1.5,
  sesame_oil: 2,
  garlic_powder: 0.8,
  ground_black_pepper: 0.25,
  lumpia_wrapper: 10,
  eggs: 17,
},

pancit_bihon: {
  pancit_bihon_noodles: 50,
  pork: 50,
  chicken: 50,
  snow_peas: 50,
  carrot: 50,
  cabbage: 50,
  celery_leaves: 50,
  onion: 50,
  garlic: 50,
  chicken_powder: 50,
  soy_sauce: 50,
  water: 50,
  cooking_oil: 50,
},

pancit_molo: {
  ground_pork: 113,
  shrimp: 25,
  wonton_wrappers: 15,
  yellow_onion: 15,
  garlic_powder: 0.25,
  sesame_oil: 0.3,
  egg: 9,
  salt: 1,
  ground_black_pepper: 0.07,
  chicken_generic_raw: 80,
  chicken_bouillon_cubes: 20,
  water: 120,
  scallions: 8,
  toasted_garlic: 5,
  fish_sauce: 6,
},


pinakbet: {
  lechon_kawali: 113,
  shrimp_bouillon_cube: 2.5,
  sitaw: 30,
  kalabasa: 60,
  okra: 30,
  chinese_eggplant: 30,
  ampalaya: 25,
  kamote: 40,
  tomato: 30,
  ginger: 5,
  onion: 25,
  garlic: 3,
  bagoong_alamang: 3,
  water: 150,
  cooking_oil: 10,
  ground_black_pepper: 0.2,
},

pork_adobo: {
  pork_belly: 227,
  garlic: 8,
  bay_leaves: 0.3,
  vinegar: 15,
  soy_sauce: 31,
  peppercorn: 2,
  water: 120,
  salt: 2,
},

pork_sinigang: {
  pork_belly: 150,
  kangkong_leaves: 20,
  long_green_chili_pepper: 5,
  tomato: 20,
  daikon_radish: 24,
  snake_beans: 15,
  onion: 15,
  okra: 20,
  taro: 11,
  water: 320,
  sinigang_sa_sampaloc_mix: 11,
  fish_sauce: 5,
  ground_black_pepper: 1,
},


pork_sisig: {
  pig_ears: 91,
  pig_snout: 91,
  pork_belly: 91,
  onion: 40,
  bay_leaves: 0.2,
  salt: 2.4,
  ginger: 8,
  water: 189,
},

pyanggang: {
  chicken_leg_quarters: 50,
  chicken_thighs: 50,
  burnt_coconut: 50,
  red_onion: 50,
  lemongrass: 50,
  luyang_dilaw: 50,
  garlic: 50,
  ginger: 50,
  cilantro_stems: 50,
  spring_onions: 50,
  canola_oil: 50,
  salt: 50,
  finger_chilies: 50,
  white_onion: 50,
  fish_sauce: 50,
  coconut_milk: 50,
  coconut_cream: 50,
},

satti: {
  beef: 83.3,
  chicken_wings: 80.0,
  coconut_milk: 20.0,
  barbecue_skewers: ~1.7,
  annatto_powder: 1.7,
  lemon_juice: 10.0,
  water: 166.7,
  salt: 0.5,
  chicken_stock: 83.3,
  coconut_cream: 5.0,
  tomato: 16.7,
  japanese_taro: 13.3,
  bagoong: 0.33,
  peanut_butter: 0.83,
  curry_powder: 0.33,
  oil: 1.67,
  flour: 1.33,
  cornstarch: 5.0,
  white_sugar: 11.2,
  birds_eye_chilies: 0.67,
  ginger: 1.67,
  shallots: 1.67,
  turmeric: 0.33,
  dried_oregano: 0.17,
},

shrimp_sinigang: {
  shrimp: 113,
  sinigang_sa_sampaloc_mix: 11,
  kangkong: 25,
  snake_beans: 38,
  okra: 15,
  eggplant: 25,
  daikon_radish: 25,
  tomato: 25,
  long_green_pepper: 8,
  onion: 25,
  water: 473,
  fish_sauce: 5,
  ground_black_pepper: 0.2,
},

tiyula_itum: {
  beef: 100,
  chicken: 100,
  ginger: 5,
  garlic: 5,
  onion: 20,
  lemongrass: 7.5,
  burnt_coconut_meat_powder: 15,
  turmeric_powder: 2.5,
}

};
